import { Forfait } from './forfait';
    
export const FORFAITS: Forfait []= [
    { 
      nom : 'Forfait Cadeaux Produit',
      description: 'Carte cadeau pour nos produit de bauté ',
      code: 1,
      categories: 'produits et équipement hôtelier',
      etablissement :'LOC International',
      coordonnees :' forfaits@loc.com',
      site_web : 'voyagesloc.com',
      details : 'fournisseur produit pour Hôtel et d hébergement à prix Abordables et produits éco-responsables',
      date_debut :new Date (24-12-2022),
      date_fin : new Date (24-1-2023),
      prix : 250,
      nouveau_prix: 230,
      economie: 20,
      premium: true,
      avis: 1758,
      note: 4.8,
      commentaires: 'Sed ut perspiciatis unde omnis',
      },
      {
      nom : 'Forfait cadeau Hébergement',
      description: 'Offre Réveillon 2023 CHAMBRE, PETIT-DÉJEUNER ET SOUPER',
      code: 2,
      categories: 'Forfait cadeau Hébergement Hotel 5 etoile',
      etablissement :'Fairmont Le Château Laurier',
      coordonnees :'abc123@laurier.com',
      site_web : 'laurierchateau.com',
      details : 'meilleur rapport qualité-prix',
      date_debut :new Date (31-12-2022),
      date_fin : new Date (2-1-2023),
      prix : 570,
      nouveau_prix: 520,
      economie: 50,
      premium: true,
      avis: 583758,
      note: 4.7,
      commentaires: 'Sed ut perspiciatis unde omnis',
      },
      {
        nom : 'Forfait cadeaux soins détente',
        description: 'Ce forfait pour deux personnes',
        code: 3,
        categories: 'Accès à l expérience thermale Hotel 5 etoile',
        etablissement :'Strom spa nordique',
        coordonnees :'abc123@rio.com',
        site_web : 'hotelrioplage.com',
        details : 'Installé sur le front de mer de Copacabana, avec une vue superbe sur la plus célèbre plage de Rio et ses eaux cristallines',
        date_debut :new Date (24-12-2022),
        date_fin : new Date (24-1-2023),
        prix : 350,
        nouveau_prix: 350,
        economie: 0,
        premium: false,
        avis: 702,
        note: 4.3/5,
        commentaires: 'Excellent',
        },
        {
          nom : 'Forfaits Cadeau Restaurant',
          description: 'CERTIFICAT-CADEAU DE 100 $',
          code: 4,
          categories: ' Menu Réveillon 2023',
          etablissement :'Portofino Bistro Italiano ',
          coordonnees :'abc123@ITAL.com',
          site_web : 'portofinio.com',
          details : 'Ce certificat-cadeau d une valeur de 100 $ est applicable sur l ensemble du menu à la carte.',
          date_debut :new Date (31-12-2022),
          date_fin : new Date (2-1-2023),
          prix : 250,
          nouveau_prix: 100,
          economie: 150,
          premium: true,
          avis: 175853,
          note: 4.7,
          commentaires: 'Excellent',
          },
          {
            nom : 'Forfait Cadeau Activités',
            description: 'Une valeur de 50 $ applicable pour des billets de ski pour la montagne de votre choix',
            code: 1,
            categories: 'Reservation Hotel 4 etoile',
            etablissement :'Hautes Montagnes du Québec ',
            coordonnees :'abc123@hmq.com',
            site_web : 'hmqvoyage.com',
            details : ' Applicable a ne réservation d un séjour dans un établissement de votre choix',
            date_debut :new Date (24-12-2022),
            date_fin : new Date (24-1-2023),
            prix : 100,
            nouveau_prix: 50,
            economie: 50,
            premium: true,
            avis: 158,
            note: 4.2,
            commentaires: 'Sed ut perspiciatis unde omnis',
            }

      ]
    
    
