import { Component, OnInit } from '@angular/core';
import { Forfait } from '../forfait';
@Component({
  selector: 'app-forfait-list',
  templateUrl: './forfait-list.component.html',
  styleUrls: ['./forfait-list.component.css']
})

export class ForfaitListComponent implements OnInit {

  forfaits: Forfait[] = []

  constructor() { }

  ngOnInit(): void {
    this.forfaits= [
      { 
        nom : 'VOYAGE DE RÊVE À DUBAI',
        description: 'Forfait 30-Jours à Dubai avec vols',
        code: 1,
        categories: 'Offre séjours',
        etablissement :'Agence de Voyages 100% Québecoise',
        coordonnees :' forfaits@wing.com',
        site_web : 'voyagesoleil.com',
        details : 'VOLS INTERNATIONAUX , ACCUEILS ET TRANSFERTS A HÔTELS, 14 REPAS, EXCURSIONS',
        date_debut :new Date (24-12-2022),
        date_fin : new Date (24-1-2023),
        prix : 2500,
        nouveau_prix: 2300,
        economie: 200,
        premium: true,
        avis: 1758,
        note: 4.8,
        commentaires: 'Sed ut perspiciatis unde omnis',
        },
        {
        nom : 'Promos séjours nouvel an',
        description: 'Réveillon 2023',
        code: 2,
        categories: 'Hotel 5 etoile',
        etablissement :'Paris Belleville',
        coordonnees :'abc123@paris.com',
        site_web : 'Parisbelleville.com',
        details : 'meilleur rapport qualité-prix à Paris',
        date_debut :new Date (31-12-2022),
        date_fin : new Date (2-1-2023),
        prix : 4500,
        nouveau_prix: 3300,
        economie: 1200,
        premium: true,
        avis: 583758,
        note: 4.7,
        commentaires: 'Sed ut perspiciatis unde omnis',
        },
        {
          nom : 'Vacances Rio de Janeiro',
          description: 'JW Marriott Hotel Rio de Janeiro',
          code: 3,
          categories: 'Hotel 5 etoile',
          etablissement :'Copacabana voyage',
          coordonnees :'abc123@rio.com',
          site_web : 'hotelrioplage.com',
          details : 'Installé sur le front de mer de Copacabana, avec une vue superbe sur la plus célèbre plage de Rio et ses eaux cristallines',
          date_debut :new Date (24-12-2022),
          date_fin : new Date (24-1-2023),
          prix : 1500,
          nouveau_prix: 1100,
          economie: 400,
          premium: true,
          avis: 702,
          note: 4.3/5,
          commentaires: 'Excellent',
          },
          {
            nom : 'Forfaits pour la Coupe du Monde 2022',
            description: 'Planifiez votre expérience de Coupe du Monde',
            code: 4,
            categories: 'Offre séjours',
            etablissement :'HAVAS VOYAGES SPORTS ',
            coordonnees :'abc123@hava.com',
            site_web : 'havavoyage.com',
            details : 'Chaque forfait inclutles vols,hébergement et les billets pour les matchs',
            date_debut :new Date (24-11-2022),
            date_fin : new Date (24-12-2023),
            prix : 8500,
            nouveau_prix: 7300,
            economie: 1000,
            premium: true,
            avis: 175853,
            note: 4.7,
            commentaires: 'Excellent',
            },
            {
              nom : 'Hotel Grand Majestic Plaza 4*',
              description: 'Week-end à Prague',
              code: 1,
              categories: 'Reservation Hotel 4 etoile',
              etablissement :'leclerc voyage',
              coordonnees :'abc123@leclerc.com',
              site_web : 'leclercvoyag.com',
              details : 'Voyages République Tchèque - Prague',
              date_debut :new Date (24-12-2022),
              date_fin : new Date (24-1-2023),
              prix : 1500,
              nouveau_prix: 1300,
              economie: 200,
              premium: false,
              avis: 158,
              note: 4.2,
              commentaires: 'Sed ut perspiciatis unde omnis',
              },
              { 
                nom : 'Forfait Cadeaux Produit',
                description: 'Carte cadeau pour nos produit de bauté ',
                code: 1,
                categories: 'produits et équipement hôtelier',
                etablissement :'LOC International',
                coordonnees :' forfaits@loc.com',
                site_web : 'voyagesloc.com',
                details : 'fournisseur produit pour Hôtel et d hébergement à prix Abordables et produits éco-responsables',
                date_debut :new Date (24-12-2022),
                date_fin : new Date (24-1-2023),
                prix : 250,
                nouveau_prix: 230,
                economie: 20,
                premium: true,
                avis: 1758,
                note: 4.8,
                commentaires: 'Sed ut perspiciatis unde omnis',
                },
                {
                nom : 'Forfait cadeau Hébergement',
                description: 'Offre Réveillon 2023 CHAMBRE, PETIT-DÉJEUNER ET SOUPER',
                code: 2,
                categories: 'Forfait cadeau Hébergement Hotel 5 etoile',
                etablissement :'Fairmont Le Château Laurier',
                coordonnees :'abc123@laurier.com',
                site_web : 'laurierchateau.com',
                details : 'meilleur rapport qualité-prix',
                date_debut :new Date (31-12-2022),
                date_fin : new Date (2-1-2023),
                prix : 570,
                nouveau_prix: 520,
                economie: 50,
                premium: true,
                avis: 583758,
                note: 4.7,
                commentaires: 'Sed ut perspiciatis unde omnis',
                },
                {
                  nom : 'Forfait cadeaux soins détente',
                  description: 'Ce forfait pour deux personnes',
                  code: 3,
                  categories: 'Accès à l expérience thermale Hotel 5 etoile',
                  etablissement :'Strom spa nordique',
                  coordonnees :'abc123@rio.com',
                  site_web : 'hotelrioplage.com',
                  details : 'Installé sur le front de mer de Copacabana, avec une vue superbe sur la plus célèbre plage de Rio et ses eaux cristallines',
                  date_debut :new Date (24-12-2022),
                  date_fin : new Date (24-1-2023),
                  prix : 350,
                  nouveau_prix: 350,
                  economie: 0,
                  premium: false,
                  avis: 702,
                  note: 4.3/5,
                  commentaires: 'Excellent',
                  },
                  {
                    nom : 'Forfaits Cadeau Restaurant',
                    description: 'CERTIFICAT-CADEAU DE 100 $',
                    code: 4,
                    categories: ' Menu Réveillon 2023',
                    etablissement :'Portofino Bistro Italiano ',
                    coordonnees :'abc123@ITAL.com',
                    site_web : 'portofinio.com',
                    details : 'Ce certificat-cadeau d une valeur de 100 $ est applicable sur l ensemble du menu à la carte.',
                    date_debut :new Date (31-12-2022),
                    date_fin : new Date (2-1-2023),
                    prix : 100,
                    nouveau_prix: 250,
                    economie: 150,
                    premium: true,
                    avis: 175853,
                    note: 4.7,
                    commentaires: 'Excellent',
                    },
                    {
                      nom : 'Forfait Cadeau Activités',
                      description: 'Une valeur de 50 $ applicable pour des billets de ski pour la montagne de votre choix',
                      code: 1,
                      categories: 'Reservation Hotel 4 etoile',
                      etablissement :'Hautes Montagnes du Québec ',
                      coordonnees :'abc123@hmq.com',
                      site_web : 'hmqvoyage.com',
                      details : ' Applicable a ne réservation d un séjour dans un établissement de votre choix',
                      date_debut :new Date (24-12-2022),
                      date_fin : new Date (24-1-2023),
                      prix : 100,
                      nouveau_prix: 50,
                      economie: 50,
                      premium: true,
                      avis: 158,
                      note: 4.2,
                      commentaires: 'Sed ut perspiciatis unde omnis',
                      },

        ]
    }
  }